id: P002969
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016236
  title: གསུང་འབུམ་། མི་འགྱུར་རྒྱལ་མཚན
  author: ''
  volumes:
    9f062f8bd4884256a8101ee3fec079ba:
      image_group_id: I00JW501109
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
